version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 8631:8000
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 8632:3000
    volumes:
      - ./frontend:/app
    command: npm start
  db:
    image: mongo
    ports:
      - 8633:27017
